<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChartOfAccountSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('chart_of_account')->insert([
            [
                'group_id' => 1,
                'parent_id' => null,
                'header' => true,
                'code' => '1000',
                'name' => 'Assets',
                'default' => 'Debet',
                'description' => 'Main asset account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 1,
                'parent_id' => 1,
                'header' => false,
                'code' => '1100',
                'name' => 'Cash',
                'default' => 'Debet',
                'description' => 'Cash account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 1,
                'parent_id' => 1,
                'header' => false,
                'code' => '1200',
                'name' => 'Accounts Receivable',
                'default' => 'Debet',
                'description' => 'Accounts receivable account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 1,
                'parent_id' => 1,
                'header' => true,
                'code' => '1300',
                'name' => 'Inventory',
                'default' => 'Debet',
                'description' => 'Inventory account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 1,
                'parent_id' => 4,
                'header' => false,
                'code' => '1310',
                'name' => 'Raw Materials',
                'default' => 'Debet',
                'description' => 'Raw materials inventory',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 1,
                'parent_id' => 4,
                'header' => false,
                'code' => '1320',
                'name' => 'Finished Goods',
                'default' => 'Debet',
                'description' => 'Finished goods inventory',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 2,
                'parent_id' => null,
                'header' => true,
                'code' => '2000',
                'name' => 'Liabilities',
                'default' => 'Credit',
                'description' => 'Main liabilities account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 2,
                'parent_id' => 7,
                'header' => false,
                'code' => '2100',
                'name' => 'Accounts Payable',
                'default' => 'Credit',
                'description' => 'Accounts payable account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 2,
                'parent_id' => 7,
                'header' => false,
                'code' => '2200',
                'name' => 'Accrued Expenses',
                'default' => 'Credit',
                'description' => 'Accrued expenses account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 2,
                'parent_id' => 7,
                'header' => true,
                'code' => '2300',
                'name' => 'Long-term Liabilities',
                'default' => 'Credit',
                'description' => 'Long-term liabilities account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 2,
                'parent_id' => 10,
                'header' => false,
                'code' => '2310',
                'name' => 'Mortgage Payable',
                'default' => 'Credit',
                'description' => 'Mortgage payable account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'group_id' => 2,
                'parent_id' => 10,
                'header' => false,
                'code' => '2320',
                'name' => 'Bonds Payable',
                'default' => 'Credit',
                'description' => 'Bonds payable account',
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
DB::table('chart_of_account')->insert([
    [
        'group_id' => 1,
        'parent_id' => null,
        'header' => true,
        'code' => '1000',
        'name' => 'Assets',
        'default' => 'Debet',
        'description' => 'Main asset account',
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'group_id' => 1,
        'parent_id' => 1,
        'header' => false,
        'code' => '1100',
        'name' => 'Cash',
        'default' => 'Debet',
        'description' => 'Cash account',
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'group_id' => 2,
        'parent_id' => null,
        'header' => true,
        'code' => '2000',
        'name' => 'Liabilities',
        'default' => 'Credit',
        'description' => 'Main liabilities account',
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'group_id' => 2,
        'parent_id' => 3,
        'header' => false,
        'code' => '2100',
        'name' => 'Accounts Payable',
        'default' => 'Credit',
        'description' => 'Accounts payable account',
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ],
]);
