<?php

namespace Database\Seeders;

use App\Models\SIMRS\Departement;
use Illuminate\Database\Seeder;

class DepartementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departements = [
            [
                'name' => 'AMBULANCE',
                'kode' => 'AMBU',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'AMBULANCE',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'ANASTESI',
                'kode' => 'ANASTESI',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'ANASTESI',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'APOTIK',
                'kode' => 'APOTIK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'APOTIK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'BABY CARE',
                'kode' => 'BABY CARE',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'BABY CARE',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'FACILITY',
                'kode' => 'FACILITY',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'FACILITY',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'FEE RUJUKAN OK',
                'kode' => 'FEE RUJUKAN OK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'FEE RUJUKAN OK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'FEE RUJUKAN VK',
                'kode' => 'FEE RUJUKAN VK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'FEE RUJUKAN VK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'HEMODIALISA',
                'kode' => 'HEMODIALISA',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'HEMODIALISA',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'HOMECARE',
                'kode' => 'HOMECARE',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'HOMECARE',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'ICU/ICCU',
                'kode' => 'ICU/ICCU',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'ICU/ICCU',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'KORESPONDEDSI',
                'kode' => 'KORESPONDEDSI',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'KORESPONDEDSI',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'MEDICAL CHECK UP',
                'kode' => 'MEDICAL CHECK UP',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'MEDICAL CHECK UP',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'PAKET PARTUS',
                'kode' => 'PAKET PARTUS',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'TINDAKAN PERAWATAN',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK BEDAH',
                'kode' => 'POLIKLINIK BEDAH',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK BEDAH',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK GIGI DAN MULUT',
                'kode' => 'POLIKLINIK GIGI DAN MULUT',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK GIGI DAN MULUT',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK OBGYN',
                'kode' => 'POLIKLINIK OBGYN',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK OBGYN',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK PENYAKIT DALAM',
                'kode' => 'POLIKLINIK PENYAKIT DALAM',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK PENYAKIT DALAM',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK REHAB MEDIK',
                'kode' => 'POLIKLINIK REHAB MEDIK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK REHAB MEDIK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK SPESIALIS ANAK',
                'kode' => 'POLIKLINIK SPESIALIS ANAK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK SPESIALIS ANAK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'POLIKLINIK UMUM',
                'kode' => 'POLIKLINIK UMUM',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'POLIKLINIK UMUM',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'RAWAT INAP',
                'kode' => 'RAWAT INAP',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'RAWAT INAP',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'REHAB MEDIK',
                'kode' => 'REHAB MEDIK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'REHAB MEDIK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'TINDAKAN KEPERAWATAN VK',
                'kode' => 'TINDAKAN KEPERAWATAN VK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'DEPO VK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'TINDAKAN PERAWATAN',
                'kode' => 'TINDAKAN PERAWATAN',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'TINDAKAN PERAWATAN',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'UGD',
                'kode' => 'UGD',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'IGD',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'UNIT GIZI',
                'kode' => 'UNIT GIZI',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'UNIT GIZI',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'UNIT LABORATORIUM',
                'kode' => 'UNIT LABORATORIUM',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'UNIT LABORATORIUM',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'UNIT RADIOLOGI',
                'kode' => 'UNIT RADIOLOGI',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'UNIT RADIOLOGI',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'UNIT REHAB MEDIK',
                'kode' => 'UNIT REHAB MEDIK',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'REHABILITASI MEDIK',
                'master_layanan_rl' => '',
            ],
            [
                'name' => 'VISITE',
                'kode' => 'VISITE',
                'keterangan' => '',
                'quota' => '',
                'kode_poli' => '',
                'publish_online' => '',
                'revenue_and_cost_center' => 'SUPERIOR',
                'master_layanan_rl' => '',
            ],
            // Tambahkan etnis lainnya di sini
        ];

        foreach ($departements as $departement) {
            Departement::create($departement);
        }
    }
}
