<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Intervention; // Pastikan path ini sesuai
use Illuminate\Support\Facades\DB;

class InterventionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Intervention::truncate();

        $interventions = [
            'Akupresur',
            'Amnioninfusion',
            'Aplikasi panas / dingin',
            'Autotranfusi',
            'Bantuan berkemih',
            'Bantuan kontrol marah',
            'Bantuan modifikasi diri',
            'Bantuan pasien untuk mengontrol pemberian analgesik',
            'Bantuan pemeriksaan',
            'Bantuan penghentian merokok',
            'Bantuan perawatan diri',
            'Bantuan perawatan diri : berpakaian / berdandan',
            'Bantuan perawatan diri : eliminasi',
            'Bantuan perawatan diri : IADL',
            'Bantuan perawatan diri : mandi / kebersihan',
            'Bantuan perawatan diri : pemberian makan',
            'Bantuan sumber keuangan',
            'Bantuan ventilasi',
            'Berpakaian',
            'Bimbingan antisipasif',
            'Dukungan emosional',
            'Dukungan kelompok',
            'Dukungan pengambilan keputusan',
            'Dukungan pengasuhan',
            'Dukungan perlindungan terhadap kekerasan : anak',
            'Dukungan spiritual',
            'Fasilitasi pengembangan spiritual',
            'Fasilitasi tanggungjawab diri',
            'Fisioterapi dada',
            'Fototerapi : neonatus',
            'Humor',
            'Identifikasi risiko',
            'Induksi melahirkan',
            'Interpretasi data laboratorium',
            'Intervensi krisis',
            'Intubasi gastrointestinal',
            'Irigasi kandung kemih',
            'Irigasi luka',
            'Kateterisasi urine',
            'Keluarga berencana : kontrasepsi',
            'Klarifikasi nilai',
            'Konseling',
            'Konseling laktasi',
            'Konseling nutrisi',
            'Kontrol infeksi',
            'Latihan asertif',
            'Latihan kandung kemih',
            'Latihan memori',
            'Latihan otot pelvis',
            'Latihan saluran cerna',
            'Manajemen alat akses vena sentral',
            'Manajemen alat pacu jantung : permanen',
            'Manajemen alat pacu jantung : sementara',
            'Manajemen alat terapi per vaginam',
            'Manajemen alergi',
            'Manajemen anafilaksis',
            'Manajemen asam basa',
            'Manajemen asam basa : alkalosis metabolik',
            'Manajemen asam basa : alkalosis respiratorik',
            'Manajemen asam basa : asidosis metabolik',
            'Manajemen asam basa : asidosis respiratorik',
            'Manajemen asma',
            'Manajemen barat badan',
            'Manajemen cairan',
            'Manajemen delirium',
            'Manajemen delusi',
            'Manajemen demensia',
            'Manajemen demensia : keluyuran',
            'Manajemen demensia : memandikan',
            'Manajemen diare',
            'Manajemen edema serebral',
            'Manajemen elektrolit',
            'Manajemen elektrolit / cairan',
            'Manajemen elektrolit : Hiperfosfatemia',
            'Manajemen elektrolit : Hiperkalemia',
            'Manajemen elektrolit : Hiperkalsemia',
            'Manajemen elektrolit : Hipermagnesemia',
            'Manajemen elektrolit : Hipernatremi',
            'Manajemen elektrolit : Hipofosfatemia',
            'Manajemen elektrolit : Hipokalemia',
            'Manajemen elektrolit : Hipokalsemia',
            'Manajemen elektrolit : Hipomagnesemia',
            'Manajemen elektrolit : Hiponatremia',
            'Manajemen gangguan makan',
            'Manajemen halusinasi',
            'Manajemen hiperglikemia',
            'Manajemen hipervolemia',
            'Manajemen hipoglikemia',
            'Manajemen hipovolemia',
            'Manajemen imunisasi',
            'Manajemen jalan nafas',
            'Manajemen jalan nafas buatan',
            'Manajemen kejang',
            'Manajemen kemoterapi',
            'Manajemen kode',
            'Manajemen konstipasi',
            'Manajemen lingkungan',
            'Manajemen lingkungan : kenyamanan',
            'Manajemen lingkungan : keselamatan',
            'Manajemen lingkungan : Keselamatan kerja',
            'Manajemen lingkungan : pencegahan kekerasan',
            'Manajemen mual',
            'Manajemen muntah',
            'Manajemen nutrisi',
            'Manajemen nyeri',
            'Manajemen penyakit menular',
            'Manajemen perilaku : menyakiti diri',
            'Manajemen perilaku seksual',
            'Manajemen prolaps rektum',
            'Manajemen pruritus',
            'Manajemen risiko jantung',
            'Manajemen saluran cerna',
            'Manajemen sedasi',
            'Manajemen sensasi perifer',
            'Manajemen syok',
            'Manajemen syok : jantung',
            'Manajemen syok : vasogenik',
            'Manajemen syok : volume',
            'Manajemen tekanan',
            'Manajemen terapi radiasi',
            'Manajemen terapi trombolitik',
            'Manajemen ventilasi mekanik : invasif',
            'Manajemen ventilasi mekanik : non invasif',
            'Manajemen ventilasi mekanik : pencegahan pneumonia',
            'Memandikan',
            'Membangun hubungan yang kompleks',
            'Mendengar aktif',
            'Menjahit luka',
            'Modifikasi perilaku',
            'Monitor asam basa',
            'Monitor cairan',
            'Monitor ekstremitas bawah',
            'Monitor elektrolit',
            'Monitor hemodinamik invasif',
            'Monitor janin secara elektronik : antepartum',
            'Monitor janin secara elektronik : intrapartum',
            'Monitor neurologi',
            'Monitor nutrisi',
            'Monitor pernafasan',
            'Monitor tekanan intra kranial',
            'Orientasi realita',
            'Panduan sistem pelayanan kesehatan',
            'Pemasangan infus',
            'Pembatasan area',
            'Pemberian analgesik',
            'Pemberian analgesik : intraspinal',
            'Pemberian anestesi',
            'Pemberian enema',
            'Pemberian makan',
            'Pemberian makan dengan botol',
            'Pemberian makan dengan cangkir : bayi baru lahir',
            'Pemberian makan dengan tabung enteral',
            'Pemberian obat : hidung',
            'Pemberian obat : inhalasi',
            'Pemberian obat : Intradermal',
            'Pemberian obat : Intramuskular',
            'Pemberian obat : intravena',
            'Pemberian obat : kulit',
            'Pemberian obat : mata',
            'Pemberian obat : Oral',
            'Pemberian obat : rektum',
            'Pemberian obat : telinga',
            'Pemberian obat : vagina',
            'Pemberian produk darah',
            'Pembidaian',
            'Pemeliharaan akses dialisis',
            'Pemeliharaan kesehatan mulut',
            'Penahapan diet',
            'Pencegahan aspirasi',
            'Pencegahan cedera olah raga : remaja',
            'Pencegahan emboli',
            'Pengajaran : latihan toilet',
            'Pengurangan perut kembung',
            'Peningkatan tidur',
            'Perawatan luka : drainage tertutup',
            'Perawatan luka : luka bakar',
            'Perawatan luka tekan',
            'Perawatan luka : tidak sembuh',
            'Perawatan mata',
            'Perawatan ostomi',
            'Perawatan paska anestesi',
            'Perawatan penggunaan zat terlarang',
            'Perawatan penggunaan zat terlarang : over dosis',
            'Perawatan penggunaan zat terlarang : putus alkohol',
            'Perawatan penggunaan zat terlarang : putus obat',
            'Perawatan perineum',
            'Perawatan persiapan kateter sentral perifer',
            'Perawatan post partum',
            'Perawatan prenatal',
            'Perawatan rambut dan kulit kepala',
            'Perawatan retensio urine',
            'Perawatan selang : gastrointestinal',
            'Perawatan selang : Tali pusat',
            'Perawatan sirkulasi : alat bantu mekanik',
            'Perawatan sirkulasi : insufisiensi arteri',
            'Perawatan sirkulasi : insufisiensi vena',
            'Supresi melahirkan',
            'Terapi latihan : keseimbangan',
            'Terapi latihan : kontrol otot',
            'Terapi latihan : pergerakan sendi',
        ];

        foreach ($interventions as $name) {
            Intervention::create([
                'name' => $name,
                'tipe_rawat' => 'all'
            ]);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
