<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAssesmentKeperawatanGadarTable extends Migration
{
    public function up()
    {
        Schema::create('assesment_keperawatan_gadar', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('registration_id')->nullable();
            $table->foreign('registration_id')->references('id')->on('registrations');
            $table->unsignedBigInteger('user_id')->nullable();
            $table->foreign('user_id')->references('id')->on('users');
            $table->date('tgl_masuk')->nullable();
            $table->time('jam_masuk')->nullable();
            $table->date('tgl_dilayani')->nullable();
            $table->time('jam_dilayani')->nullable();
            $table->text('keluhan_utama')->nullable();
            $table->text('riwayat_pengobatan')->nullable();
            $table->text('riwayat_penyakit_keluarga')->nullable();
            $table->string('diagnosa_keperawatan_1')->nullable();
            $table->string('rencana_tindak_lanjut_1')->nullable();
            $table->string('diagnosa_keperawatan_2')->nullable();
            $table->string('rencana_tindak_lanjut_2')->nullable();
            $table->string('diagnosa_keperawatan_3')->nullable();
            $table->string('rencana_tindak_lanjut_3')->nullable();
            $table->boolean('kasus_trauma')->nullable();
            $table->boolean('kasus_non_trauma')->nullable();
            $table->boolean('kasus_obstetri')->nullable();
            $table->boolean('kasus_rujukan')->nullable();
            $table->boolean('kasus_tanda_kedukaan')->nullable();
            $table->boolean('kasus_apneu')->nullable();
            $table->string('transportasi_igd')->nullable();
            $table->string('spesialistik')->nullable();
            $table->boolean('hambatan_tidak_ada')->nullable();
            $table->boolean('hambatan_bahasa')->nullable();
            $table->boolean('hambatan_fisik')->nullable();
            $table->boolean('hambatan_tuli')->nullable();
            $table->boolean('hambatan_bisu')->nullable();
            $table->boolean('hambatan_buta')->nullable();
            $table->string('pra_tinggi_badan')->nullable();
            $table->string('pra_berat_badan')->nullable();
            $table->string('pra_gcs')->nullable();
            $table->string('pra_tekanan_darah')->nullable();
            $table->string('pra_nadi')->nullable();
            $table->string('pra_suhu')->nullable();
            $table->string('pra_rr')->nullable();
            $table->string('pra_sp02')->nullable();
            $table->string('pra_o2')->nullable();
            $table->string('pra_data_penunjang')->nullable();
            $table->string('pra_obat_infus')->nullable();
            $table->string('pra_alasan_dirujuk')->nullable();
            $table->string('pra_lain_lain')->nullable();
            $table->string('status_psikologis')->nullable();
            $table->string('status_mental')->nullable();
            $table->string('masalah_perilaku')->nullable();
            $table->string('kekerasan')->nullable();
            $table->string('hubungan_keluarga')->nullable();
            $table->string('tempat_tinggal')->nullable();
            $table->string('kerabat_dihubungi')->nullable();
            $table->string('kontak_kerabat')->nullable();
            $table->string('status_perkawinan')->nullable();
            $table->string('pekerjaan')->nullable();
            $table->string('agama')->nullable();
            $table->string('penghasilan')->nullable();
            $table->string('pendidikan')->nullable();
            $table->string('skala_nyeri')->nullable();
            $table->string('nyeri_provokatif')->nullable();
            $table->string('nyeri_quality')->nullable();
            $table->string('nyeri_region')->nullable();
            $table->string('nyeri_time')->nullable();
            $table->string('nyeri')->nullable();
            $table->text('nyeri_hilang_apabila')->nullable();
            $table->string('flacc_wajah')->nullable();
            $table->string('flacc_kaki')->nullable();
            $table->string('flacc_aktivitas')->nullable();
            $table->string('flacc_menangis')->nullable();
            $table->string('flacc_bersuara')->nullable();
            $table->string('flacc_skor')->nullable();
            $table->string('keadaan_umum')->nullable();
            $table->string('berjalan_stabil')->nullable();
            $table->string('alat_bantu')->nullable();
            $table->string('pegang_meja')->nullable();
            $table->string('gizi_penurunan_bb')->nullable();
            $table->string('gizi_asupan_makanan')->nullable();
            $table->boolean('gizi_kondisi_anak')->nullable();
            $table->boolean('gizi_kondisi_lansia')->nullable();
            $table->boolean('gizi_kondisi_komplikasi')->nullable();
            $table->boolean('gizi_kondisi_kanker')->nullable();
            $table->boolean('gizi_kondisi_hiv')->nullable();
            $table->boolean('gizi_kondisi_tb')->nullable();
            $table->boolean('gizi_kondisi_bedah')->nullable();
            $table->boolean('gizi_kondisi_luka')->nullable();
            $table->string('barthel_makan')->nullable();
            $table->string('barthel_mandi')->nullable();
            $table->string('barthel_berhias')->nullable();
            $table->string('barthel_berpakaian')->nullable();
            $table->string('barthel_bab')->nullable();
            $table->string('barthel_bak')->nullable();
            $table->string('barthel_toileting')->nullable();
            $table->string('barthel_transfer')->nullable();
            $table->string('barthel_mobilitas')->nullable();
            $table->string('barthel_naik_tangga')->nullable();
            $table->string('barthel_skor')->nullable();
            $table->text('barthel_analisa')->nullable();
            $table->text('discharge_kondisi_umur65')->nullable();
            $table->text('discharge_kondisi_mobilitas')->nullable();
            $table->text('discharge_perawatan_lanjutan')->nullable();
            $table->text('discharge_bantuan_aktivitas')->nullable();
            $table->text('discharge_perawatan_diri')->nullable();
            $table->text('discharge_pemberian_obat')->nullable();
            $table->text('discharge_pendamping_tenaga')->nullable();
            $table->text('discharge_bantuan_medis')->nullable();
            $table->text('discharge_pemantauan_diet')->nullable();
            $table->text('discharge_perawatan_luka')->nullable();
            $table->text('discharge_latihan_fisik')->nullable();
            $table->text('discharge_bantuan_aktivitas_fisik')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down()
    {
        Schema::dropIfExists('assesment_keperawatan_gadar');
    }
}
